const countryCodes = [
  {
    code: "+93",
    country: "AF",
    flag: "🇦🇫",
    name: "Afghanistan",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+355",
    country: "AL",
    flag: "🇦🇱",
    name: "Albania",
    pattern: /^[6|4]\d{8}$/,
  },
  {
    code: "+213",
    country: "DZ",
    flag: "🇩🇿",
    name: "Algeria",
    pattern: /^[5|6|7]\d{8}$/,
  },
  {
    code: "+1-684",
    country: "AS",
    flag: "🇦🇸",
    name: "American Samoa",
    pattern: /^\d{7}$/,
  },
  {
    code: "+376",
    country: "AD",
    flag: "🇦🇩",
    name: "Andorra",
    pattern: /^[3|4|6]\d{5}$/,
  },
  {
    code: "+244",
    country: "AO",
    flag: "🇦🇴",
    name: "Angola",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+1-264",
    country: "AI",
    flag: "🇦🇮",
    name: "Anguilla",
    pattern: /^[2|5|7]\d{6}$/,
  },
  {
    code: "+1-268",
    country: "AG",
    flag: "🇦🇬",
    name: "Antigua and Barbuda",
    pattern: /^[2|7]\d{6}$/,
  },
  {
    code: "+54",
    country: "AR",
    flag: "🇦🇷",
    name: "Argentina",
    pattern: /^[11|[2368]\d]\d{8}$/,
  },
  {
    code: "+374",
    country: "AM",
    flag: "🇦🇲",
    name: "Armenia",
    pattern: /^[4|9]\d{7}$/,
  },
  {
    code: "+297",
    country: "AW",
    flag: "🇦🇼",
    name: "Aruba",
    pattern: /^[5|6|7|9]\d{6}$/,
  },
  {
    code: "+61",
    country: "AU",
    flag: "🇦🇺",
    name: "Australia",
    pattern: /^4\d{8}$/,
  },
  {
    code: "+43",
    country: "AT",
    flag: "🇦🇹",
    name: "Austria",
    pattern: /^6\d{8,9}$/,
  },
  {
    code: "+994",
    country: "AZ",
    flag: "🇦🇿",
    name: "Azerbaijan",
    pattern: /^[4|5|9]\d{8}$/,
  },
  {
    code: "+1-242",
    country: "BS",
    flag: "🇧🇸",
    name: "Bahamas",
    pattern: /^[3|4|5|6|7]\d{6}$/,
  },
  {
    code: "+973",
    country: "BH",
    flag: "🇧🇭",
    name: "Bahrain",
    pattern: /^[3|6]\d{7}$/,
  },
  {
    code: "+880",
    country: "BD",
    flag: "🇧🇩",
    name: "Bangladesh",
    pattern: /^1\d{9}$/,
  },
  {
    code: "+1-246",
    country: "BB",
    flag: "🇧🇧",
    name: "Barbados",
    pattern: /^[2|4]\d{6}$/,
  },
  {
    code: "+375",
    country: "BY",
    flag: "🇧🇾",
    name: "Belarus",
    pattern: /^[1|2|3|4|5|6|7|9]\d{8}$/,
  },
  {
    code: "+32",
    country: "BE",
    flag: "🇧🇪",
    name: "Belgium",
    pattern: /^4\d{8}$/,
  },
  {
    code: "+501",
    country: "BZ",
    flag: "🇧🇿",
    name: "Belize",
    pattern: /^[6]\d{6}$/,
  },
  {
    code: "+229",
    country: "BJ",
    flag: "🇧🇯",
    name: "Benin",
    pattern: /^[4|9]\d{7}$/,
  },
  {
    code: "+1-441",
    country: "BM",
    flag: "🇧🇲",
    name: "Bermuda",
    pattern: /^[5|7]\d{6}$/,
  },
  {
    code: "+975",
    country: "BT",
    flag: "🇧🇹",
    name: "Bhutan",
    pattern: /^[1|7]\d{7}$/,
  },
  {
    code: "+591",
    country: "BO",
    flag: "🇧🇴",
    name: "Bolivia",
    pattern: /^[6|7]\d{7}$/,
  },
  {
    code: "+387",
    country: "BA",
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
    pattern: /^[6]\d{7,8}$/,
  },
  {
    code: "+267",
    country: "BW",
    flag: "🇧🇼",
    name: "Botswana",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+55",
    country: "BR",
    flag: "🇧🇷",
    name: "Brazil",
    pattern: /^[1-9]{2}9?\d{8}$/,
  },
  {
    code: "+246",
    country: "IO",
    flag: "🇮🇴",
    name: "British Indian Ocean Territory",
    pattern: /^\d{7}$/,
  },
  {
    code: "+1-284",
    country: "VG",
    flag: "🇻🇬",
    name: "British Virgin Islands",
    pattern: /^[2|3|4]\d{6}$/,
  },
  {
    code: "+673",
    country: "BN",
    flag: "🇧🇳",
    name: "Brunei",
    pattern: /^[7|8]\d{6}$/,
  },
  {
    code: "+359",
    country: "BG",
    flag: "🇧🇬",
    name: "Bulgaria",
    pattern: /^[4|8|9]\d{7,8}$/,
  },
  {
    code: "+226",
    country: "BF",
    flag: "🇧🇫",
    name: "Burkina Faso",
    pattern: /^[5|6|7]\d{7}$/,
  },
  {
    code: "+257",
    country: "BI",
    flag: "🇧🇮",
    name: "Burundi",
    pattern: /^[7|2|5|6]\d{7}$/,
  },
  {
    code: "+855",
    country: "KH",
    flag: "🇰🇭",
    name: "Cambodia",
    pattern: /^[1]\d{8}$/,
  },
  {
    code: "+237",
    country: "CM",
    flag: "🇨🇲",
    name: "Cameroon",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+1",
    country: "CA",
    flag: "🇨🇦",
    name: "Canada",
    pattern: /^[2-9]\d{9}$/,
  },
  {
    code: "+238",
    country: "CV",
    flag: "🇨🇻",
    name: "Cape Verde",
    pattern: /^[5|9]\d{6}$/,
  },
  {
    code: "+1-345",
    country: "KY",
    flag: "🇰🇾",
    name: "Cayman Islands",
    pattern: /^[3|4|5|9]\d{6}$/,
  },
  {
    code: "+236",
    country: "CF",
    flag: "🇨🇫",
    name: "Central African Republic",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+235",
    country: "TD",
    flag: "🇹🇩",
    name: "Chad",
    pattern: /^[6|9]\d{7}$/,
  },
  {
    code: "+56",
    country: "CL",
    flag: "🇨🇱",
    name: "Chile",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+86",
    country: "CN",
    flag: "🇨🇳",
    name: "China",
    pattern: /^1[3-9]\d{9}$/,
  },
  {
    code: "+61",
    country: "CX",
    flag: "🇨🇽",
    name: "Christmas Island",
    pattern: /^4\d{8}$/,
  },
  {
    code: "+61",
    country: "CC",
    flag: "🇨🇨",
    name: "Cocos Islands",
    pattern: /^4\d{8}$/,
  },
  {
    code: "+57",
    country: "CO",
    flag: "🇨🇴",
    name: "Colombia",
    pattern: /^3\d{9}$/,
  },
  {
    code: "+269",
    country: "KM",
    flag: "🇰🇲",
    name: "Comoros",
    pattern: /^[3|7]\d{6}$/,
  },
  {
    code: "+682",
    country: "CK",
    flag: "🇨🇰",
    name: "Cook Islands",
    pattern: /^[5|7]\d{4}$/,
  },
  {
    code: "+506",
    country: "CR",
    flag: "🇨🇷",
    name: "Costa Rica",
    pattern: /^[6|7|8]\d{7}$/,
  },
  {
    code: "+385",
    country: "HR",
    flag: "🇭🇷",
    name: "Croatia",
    pattern: /^[9|1]\d{8}$/,
  },
  {
    code: "+53",
    country: "CU",
    flag: "🇨🇺",
    name: "Cuba",
    pattern: /^[5]\d{7}$/,
  },
  {
    code: "+599",
    country: "CW",
    flag: "🇨🇼",
    name: "Curaçao",
    pattern: /^[9]\d{6}$/,
  },
  {
    code: "+357",
    country: "CY",
    flag: "🇨🇾",
    name: "Cyprus",
    pattern: /^[9]\d{7}$/,
  },
  {
    code: "+420",
    country: "CZ",
    flag: "🇨🇿",
    name: "Czech Republic",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+243",
    country: "CD",
    flag: "🇨🇩",
    name: "Democratic Republic of the Congo",
    pattern: /^[8|9]\d{8}$/,
  },
  {
    code: "+45",
    country: "DK",
    flag: "🇩🇰",
    name: "Denmark",
    pattern: /^[2-9]\d{7}$/,
  },
  {
    code: "+253",
    country: "DJ",
    flag: "🇩🇯",
    name: "Djibouti",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+1-767",
    country: "DM",
    flag: "🇩🇲",
    name: "Dominica",
    pattern: /^[7]\d{6}$/,
  },
  {
    code: "+1-809",
    country: "DO",
    flag: "🇩🇴",
    name: "Dominican Republic",
    pattern: /^[8]\d{9}$/,
  },
  {
    code: "+670",
    country: "TL",
    flag: "🇹🇱",
    name: "East Timor",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+593",
    country: "EC",
    flag: "🇪🇨",
    name: "Ecuador",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+20",
    country: "EG",
    flag: "🇪🇬",
    name: "Egypt",
    pattern: /^1[0-2|5]\d{8}$/,
  },
  {
    code: "+503",
    country: "SV",
    flag: "🇸🇻",
    name: "El Salvador",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+240",
    country: "GQ",
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    pattern: /^[2|5]\d{8}$/,
  },
  {
    code: "+291",
    country: "ER",
    flag: "🇪🇷",
    name: "Eritrea",
    pattern: /^[7]\d{6}$/,
  },
  {
    code: "+372",
    country: "EE",
    flag: "🇪🇪",
    name: "Estonia",
    pattern: /^[5|8]\d{6,7}$/,
  },
  {
    code: "+251",
    country: "ET",
    flag: "🇪🇹",
    name: "Ethiopia",
    pattern: /^[79]\d{8}$/,
  },
  {
    code: "+500",
    country: "FK",
    flag: "🇫🇰",
    name: "Falkland Islands",
    pattern: /^[5|6]\d{4}$/,
  },
  {
    code: "+298",
    country: "FO",
    flag: "🇫🇴",
    name: "Faroe Islands",
    pattern: /^[2|5|6]\d{5}$/,
  },
  {
    code: "+679",
    country: "FJ",
    flag: "🇫🇯",
    name: "Fiji",
    pattern: /^[7|9]\d{6}$/,
  },
  {
    code: "+358",
    country: "FI",
    flag: "🇫🇮",
    name: "Finland",
    pattern: /^[4|5]\d{8}$/,
  },
  {
    code: "+33",
    country: "FR",
    flag: "🇫🇷",
    name: "France",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+594",
    country: "GF",
    flag: "🇬🇫",
    name: "French Guiana",
    pattern: /^[6]\d{8}$/,
  },
  {
    code: "+689",
    country: "PF",
    flag: "🇵🇫",
    name: "French Polynesia",
    pattern: /^[8|9]\d{5}$/,
  },
  {
    code: "+241",
    country: "GA",
    flag: "🇬🇦",
    name: "Gabon",
    pattern: /^[0|1|2|4|5|6|7]\d{6}$/,
  },
  {
    code: "+220",
    country: "GM",
    flag: "🇬🇲",
    name: "Gambia",
    pattern: /^[7|9]\d{6}$/,
  },
  {
    code: "+995",
    country: "GE",
    flag: "🇬🇪",
    name: "Georgia",
    pattern: /^[5|7]\d{8}$/,
  },
  {
    code: "+49",
    country: "DE",
    flag: "🇩🇪",
    name: "Germany",
    pattern: /^1[5-7]\d{8,9}$/,
  },
  {
    code: "+233",
    country: "GH",
    flag: "🇬🇭",
    name: "Ghana",
    pattern: /^[2|5]\d{8}$/,
  },
  {
    code: "+350",
    country: "GI",
    flag: "🇬🇮",
    name: "Gibraltar",
    pattern: /^[5|6]\d{7}$/,
  },
  {
    code: "+30",
    country: "GR",
    flag: "🇬🇷",
    name: "Greece",
    pattern: /^[6|7]\d{9}$/,
  },
  {
    code: "+299",
    country: "GL",
    flag: "🇬🇱",
    name: "Greenland",
    pattern: /^[2|5]\d{5}$/,
  },
  {
    code: "+1-473",
    country: "GD",
    flag: "🇬🇩",
    name: "Grenada",
    pattern: /^[4]\d{6}$/,
  },
  {
    code: "+590",
    country: "GP",
    flag: "🇬🇵",
    name: "Guadeloupe",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+1-671",
    country: "GU",
    flag: "🇬🇺",
    name: "Guam",
    pattern: /^[6|7]\d{6}$/,
  },
  {
    code: "+502",
    country: "GT",
    flag: "🇬🇹",
    name: "Guatemala",
    pattern: /^[3|4|5]\d{7}$/,
  },
  {
    code: "+44-1481",
    country: "GG",
    flag: "🇬🇬",
    name: "Guernsey",
    pattern: /^[7]\d{6,9}$/,
  },
  {
    code: "+224",
    country: "GN",
    flag: "🇬🇳",
    name: "Guinea",
    pattern: /^[6]\d{8}$/,
  },
  {
    code: "+245",
    country: "GW",
    flag: "🇬🇼",
    name: "Guinea-Bissau",
    pattern: /^[5|6|7]\d{7}$/,
  },
  {
    code: "+592",
    country: "GY",
    flag: "🇬🇾",
    name: "Guyana",
    pattern: /^[6]\d{6}$/,
  },
  {
    code: "+509",
    country: "HT",
    flag: "🇭🇹",
    name: "Haiti",
    pattern: /^[3|4]\d{7}$/,
  },
  {
    code: "+504",
    country: "HN",
    flag: "🇭🇳",
    name: "Honduras",
    pattern: /^[3|8|9]\d{7}$/,
  },
  {
    code: "+852",
    country: "HK",
    flag: "🇭🇰",
    name: "Hong Kong",
    pattern: /^[5|6|9]\d{7}$/,
  },
  {
    code: "+36",
    country: "HU",
    flag: "🇭🇺",
    name: "Hungary",
    pattern: /^[2|3|7]\d{8}$/,
  },
  {
    code: "+354",
    country: "IS",
    flag: "🇮🇸",
    name: "Iceland",
    pattern: /^[6|7|8]\d{6}$/,
  },
  {
    code: "+91",
    country: "IN",
    flag: "🇮🇳",
    name: "India",
    pattern: /^[6-9]\d{9}$/,
  },
  {
    code: "+62",
    country: "ID",
    flag: "🇮🇩",
    name: "Indonesia",
    pattern: /^8\d{9,10}$/,
  },
  { code: "+98", country: "IR", flag: "🇮🇷", name: "Iran", pattern: /^9\d{9}$/ },
  {
    code: "+964",
    country: "IQ",
    flag: "🇮🇶",
    name: "Iraq",
    pattern: /^7\d{9}$/,
  },
  {
    code: "+353",
    country: "IE",
    flag: "🇮🇪",
    name: "Ireland",
    pattern: /^[8]\d{8}$/,
  },
  {
    code: "+44-1624",
    country: "IM",
    flag: "🇮🇲",
    name: "Isle of Man",
    pattern: /^[7]\d{9}$/,
  },
  {
    code: "+972",
    country: "IL",
    flag: "🇮🇱",
    name: "Israel",
    pattern: /^[5]\d{8}$/,
  },
  {
    code: "+39",
    country: "IT",
    flag: "🇮🇹",
    name: "Italy",
    pattern: /^[3]\d{9}$/,
  },
  {
    code: "+225",
    country: "CI",
    flag: "🇨🇮",
    name: "Ivory Coast",
    pattern: /^[0|4|5|6|7|8]\d{7}$/,
  },
  {
    code: "+1-876",
    country: "JM",
    flag: "🇯🇲",
    name: "Jamaica",
    pattern: /^[8|9]\d{6}$/,
  },
  {
    code: "+81",
    country: "JP",
    flag: "🇯🇵",
    name: "Japan",
    pattern: /^[7|8|9]0\d{8}$/,
  },
  {
    code: "+44-1534",
    country: "JE",
    flag: "🇯🇪",
    name: "Jersey",
    pattern: /^[7]\d{9}$/,
  },
  {
    code: "+962",
    country: "JO",
    flag: "🇯🇴",
    name: "Jordan",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+7",
    country: "KZ",
    flag: "🇰🇿",
    name: "Kazakhstan",
    pattern: /^[7]\d{9}$/,
  },
  {
    code: "+254",
    country: "KE",
    flag: "🇰🇪",
    name: "Kenya",
    pattern: /^[7|1]\d{8}$/,
  },
  {
    code: "+686",
    country: "KI",
    flag: "🇰🇮",
    name: "Kiribati",
    pattern: /^[7]\d{5}$/,
  },
  {
    code: "+383",
    country: "XK",
    flag: "🇽🇰",
    name: "Kosovo",
    pattern: /^[4]\d{7}$/,
  },
  {
    code: "+965",
    country: "KW",
    flag: "🇰🇼",
    name: "Kuwait",
    pattern: /^[5|6|9]\d{7}$/,
  },
  {
    code: "+996",
    country: "KG",
    flag: "🇰🇬",
    name: "Kyrgyzstan",
    pattern: /^[5|7]\d{8}$/,
  },
  {
    code: "+856",
    country: "LA",
    flag: "🇱🇦",
    name: "Laos",
    pattern: /^[2]\d{8}$/,
  },
  {
    code: "+371",
    country: "LV",
    flag: "🇱🇻",
    name: "Latvia",
    pattern: /^[2]\d{7}$/,
  },
  {
    code: "+961",
    country: "LB",
    flag: "🇱🇧",
    name: "Lebanon",
    pattern: /^[3|7]\d{6}$/,
  },
  {
    code: "+266",
    country: "LS",
    flag: "🇱🇸",
    name: "Lesotho",
    pattern: /^[5|6]\d{7}$/,
  },
  {
    code: "+231",
    country: "LR",
    flag: "🇱🇷",
    name: "Liberia",
    pattern: /^[4|5|6|7]\d{7}$/,
  },
  {
    code: "+218",
    country: "LY",
    flag: "🇱🇾",
    name: "Libya",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+423",
    country: "LI",
    flag: "🇱🇮",
    name: "Liechtenstein",
    pattern: /^[6|7]\d{7}$/,
  },
  {
    code: "+370",
    country: "LT",
    flag: "🇱🇹",
    name: "Lithuania",
    pattern: /^[6]\d{7}$/,
  },
  {
    code: "+352",
    country: "LU",
    flag: "🇱🇺",
    name: "Luxembourg",
    pattern: /^[6]\d{8}$/,
  },
  {
    code: "+853",
    country: "MO",
    flag: "🇲🇴",
    name: "Macau",
    pattern: /^[6]\d{7}$/,
  },
  {
    code: "+389",
    country: "MK",
    flag: "🇲🇰",
    name: "Macedonia",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+261",
    country: "MG",
    flag: "🇲🇬",
    name: "Madagascar",
    pattern: /^[3]\d{8}$/,
  },
  {
    code: "+265",
    country: "MW",
    flag: "🇲🇼",
    name: "Malawi",
    pattern: /^[7|8|9]\d{7}$/,
  },
  {
    code: "+60",
    country: "MY",
    flag: "🇲🇾",
    name: "Malaysia",
    pattern: /^1\d{8,9}$/,
  },
  {
    code: "+960",
    country: "MV",
    flag: "🇲🇻",
    name: "Maldives",
    pattern: /^[7|9]\d{6}$/,
  },
  {
    code: "+223",
    country: "ML",
    flag: "🇲🇱",
    name: "Mali",
    pattern: /^[6|7]\d{7}$/,
  },
  {
    code: "+356",
    country: "MT",
    flag: "🇲🇹",
    name: "Malta",
    pattern: /^[7|9|2]\d{7}$/,
  },
  {
    code: "+692",
    country: "MH",
    flag: "🇲🇭",
    name: "Marshall Islands",
    pattern: /^[2|4|5|6]\d{6}$/,
  },
  {
    code: "+596",
    country: "MQ",
    flag: "🇲🇶",
    name: "Martinique",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+222",
    country: "MR",
    flag: "🇲🇷",
    name: "Mauritania",
    pattern: /^[2|3|4]\d{7}$/,
  },
  {
    code: "+230",
    country: "MU",
    flag: "🇲🇺",
    name: "Mauritius",
    pattern: /^[5|7]\d{7}$/,
  },
  {
    code: "+262",
    country: "YT",
    flag: "🇾🇹",
    name: "Mayotte",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+52",
    country: "MX",
    flag: "🇲🇽",
    name: "Mexico",
    pattern: /^[1-9]\d{9}$/,
  },
  {
    code: "+691",
    country: "FM",
    flag: "🇫🇲",
    name: "Micronesia",
    pattern: /^[3|9]\d{6}$/,
  },
  {
    code: "+373",
    country: "MD",
    flag: "🇲🇩",
    name: "Moldova",
    pattern: /^[6|7]\d{7}$/,
  },
  {
    code: "+377",
    country: "MC",
    flag: "🇲🇨",
    name: "Monaco",
    pattern: /^[4|6]\d{8}$/,
  },
  {
    code: "+976",
    country: "MN",
    flag: "🇲🇳",
    name: "Mongolia",
    pattern: /^[5|8|9]\d{7}$/,
  },
  {
    code: "+382",
    country: "ME",
    flag: "🇲🇪",
    name: "Montenegro",
    pattern: /^[6|7]\d{7}$/,
  },
  {
    code: "+1-664",
    country: "MS",
    flag: "🇲🇸",
    name: "Montserrat",
    pattern: /^[2|5|6|7|8]\d{6}$/,
  },
  {
    code: "+212",
    country: "MA",
    flag: "🇲🇦",
    name: "Morocco",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+258",
    country: "MZ",
    flag: "🇲🇿",
    name: "Mozambique",
    pattern: /^[8|9]\d{7}$/,
  },
  {
    code: "+95",
    country: "MM",
    flag: "🇲🇲",
    name: "Myanmar",
    pattern: /^[7|9]\d{8,9}$/,
  },
  {
    code: "+264",
    country: "NA",
    flag: "🇳🇦",
    name: "Namibia",
    pattern: /^[6|8]\d{7}$/,
  },
  {
    code: "+674",
    country: "NR",
    flag: "🇳🇷",
    name: "Nauru",
    pattern: /^[5|7|8]\d{5}$/,
  },
  {
    code: "+977",
    country: "NP",
    flag: "🇳🇵",
    name: "Nepal",
    pattern: /^[9]\d{9}$/,
  },
  {
    code: "+31",
    country: "NL",
    flag: "🇳🇱",
    name: "Netherlands",
    pattern: /^[6]\d{8}$/,
  },
  {
    code: "+687",
    country: "NC",
    flag: "🇳🇨",
    name: "New Caledonia",
    pattern: /^[7|8|9]\d{6}$/,
  },
  {
    code: "+64",
    country: "NZ",
    flag: "🇳🇿",
    name: "New Zealand",
    pattern: /^[2|3|4|5|6|7|8|9]\d{7,8}$/,
  },
  {
    code: "+505",
    country: "NI",
    flag: "🇳🇮",
    name: "Nicaragua",
    pattern: /^[5|7|8]\d{7}$/,
  },
  {
    code: "+227",
    country: "NE",
    flag: "🇳🇪",
    name: "Niger",
    pattern: /^[8|9]\d{7}$/,
  },
  {
    code: "+234",
    country: "NG",
    flag: "🇳🇬",
    name: "Nigeria",
    pattern: /^[7|8|9]\d{9}$/,
  },
  {
    code: "+683",
    country: "NU",
    flag: "🇳🇺",
    name: "Niue",
    pattern: /^[4|7]\d{3}$/,
  },
  {
    code: "+672",
    country: "NF",
    flag: "🇳🇫",
    name: "Norfolk Island",
    pattern: /^[3|5|8]\d{5}$/,
  },
  {
    code: "+850",
    country: "KP",
    flag: "🇰🇵",
    name: "North Korea",
    pattern: /^[1|2]\d{8}$/,
  },
  {
    code: "+1-670",
    country: "MP",
    flag: "🇲🇵",
    name: "Northern Mariana Islands",
    pattern: /^[6|7]\d{6}$/,
  },
  {
    code: "+47",
    country: "NO",
    flag: "🇳🇴",
    name: "Norway",
    pattern: /^[4|9]\d{7}$/,
  },
  {
    code: "+968",
    country: "OM",
    flag: "🇴🇲",
    name: "Oman",
    pattern: /^[7|9]\d{7}$/,
  },
  {
    code: "+92",
    country: "PK",
    flag: "🇵🇰",
    name: "Pakistan",
    pattern: /^[3]\d{9}$/,
  },
  {
    code: "+680",
    country: "PW",
    flag: "🇵🇼",
    name: "Palau",
    pattern: /^[6|7|8]\d{6}$/,
  },
  {
    code: "+970",
    country: "PS",
    flag: "🇵🇸",
    name: "Palestine",
    pattern: /^[5|9]\d{8}$/,
  },
  {
    code: "+507",
    country: "PA",
    flag: "🇵🇦",
    name: "Panama",
    pattern: /^[6]\d{7}$/,
  },
  {
    code: "+675",
    country: "PG",
    flag: "🇵🇬",
    name: "Papua New Guinea",
    pattern: /^[7]\d{7}$/,
  },
  {
    code: "+595",
    country: "PY",
    flag: "🇵🇾",
    name: "Paraguay",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+51",
    country: "PE",
    flag: "🇵🇪",
    name: "Peru",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+63",
    country: "PH",
    flag: "🇵🇭",
    name: "Philippines",
    pattern: /^[9]\d{9}$/,
  },
  {
    code: "+48",
    country: "PL",
    flag: "🇵🇱",
    name: "Poland",
    pattern: /^[5|6|7|8|9]\d{8}$/,
  },
  {
    code: "+351",
    country: "PT",
    flag: "🇵🇹",
    name: "Portugal",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+1-787",
    country: "PR",
    flag: "🇵🇷",
    name: "Puerto Rico",
    pattern: /^[7|8|9]\d{9}$/,
  },
  {
    code: "+974",
    country: "QA",
    flag: "🇶🇦",
    name: "Qatar",
    pattern: /^[3|5|6|7]\d{7}$/,
  },
  {
    code: "+242",
    country: "CG",
    flag: "🇨🇬",
    name: "Republic of the Congo",
    pattern: /^[0|5|6]\d{8}$/,
  },
  {
    code: "+262",
    country: "RE",
    flag: "🇷🇪",
    name: "Reunion",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+40",
    country: "RO",
    flag: "🇷🇴",
    name: "Romania",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+7",
    country: "RU",
    flag: "🇷🇺",
    name: "Russia",
    pattern: /^[9]\d{9}$/,
  },
  {
    code: "+250",
    country: "RW",
    flag: "🇷🇼",
    name: "Rwanda",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+590",
    country: "BL",
    flag: "🇧🇱",
    name: "Saint Barthelemy",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+290",
    country: "SH",
    flag: "🇸🇭",
    name: "Saint Helena",
    pattern: /^[5|6]\d{4}$/,
  },
  {
    code: "+1-869",
    country: "KN",
    flag: "🇰🇳",
    name: "Saint Kitts and Nevis",
    pattern: /^[5|6|7]\d{6}$/,
  },
  {
    code: "+1-758",
    country: "LC",
    flag: "🇱🇨",
    name: "Saint Lucia",
    pattern: /^[5|7]\d{6}$/,
  },
  {
    code: "+590",
    country: "MF",
    flag: "🇲🇫",
    name: "Saint Martin",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+508",
    country: "PM",
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
    pattern: /^[5|6]\d{5}$/,
  },
  {
    code: "+1-784",
    country: "VC",
    flag: "🇻🇨",
    name: "Saint Vincent and the Grenadines",
    pattern: /^[4|5]\d{6}$/,
  },
  {
    code: "+685",
    country: "WS",
    flag: "🇼🇸",
    name: "Samoa",
    pattern: /^[7]\d{6}$/,
  },
  {
    code: "+378",
    country: "SM",
    flag: "🇸🇲",
    name: "San Marino",
    pattern: /^[6]\d{7,8}$/,
  },
  {
    code: "+239",
    country: "ST",
    flag: "🇸🇹",
    name: "Sao Tome and Principe",
    pattern: /^[9]\d{6}$/,
  },
  {
    code: "+966",
    country: "SA",
    flag: "🇸🇦",
    name: "Saudi Arabia",
    pattern: /^[5]\d{8}$/,
  },
  {
    code: "+221",
    country: "SN",
    flag: "🇸🇳",
    name: "Senegal",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+381",
    country: "RS",
    flag: "🇷🇸",
    name: "Serbia",
    pattern: /^[6]\d{7,8}$/,
  },
  {
    code: "+248",
    country: "SC",
    flag: "🇸🇨",
    name: "Seychelles",
    pattern: /^[2|7]\d{6}$/,
  },
  {
    code: "+232",
    country: "SL",
    flag: "🇸🇱",
    name: "Sierra Leone",
    pattern: /^[2|3|7|9]\d{7}$/,
  },
  {
    code: "+65",
    country: "SG",
    flag: "🇸🇬",
    name: "Singapore",
    pattern: /^[8|9]\d{7}$/,
  },
  {
    code: "+1-721",
    country: "SX",
    flag: "🇸🇽",
    name: "Sint Maarten",
    pattern: /^[5|7]\d{6}$/,
  },
  {
    code: "+421",
    country: "SK",
    flag: "🇸🇰",
    name: "Slovakia",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+386",
    country: "SI",
    flag: "🇸🇮",
    name: "Slovenia",
    pattern: /^[3|4|5|6|7]\d{7}$/,
  },
  {
    code: "+677",
    country: "SB",
    flag: "🇸🇧",
    name: "Solomon Islands",
    pattern: /^[7|8]\d{6}$/,
  },
  {
    code: "+252",
    country: "SO",
    flag: "🇸🇴",
    name: "Somalia",
    pattern: /^[6|7|9]\d{7}$/,
  },
  {
    code: "+27",
    country: "ZA",
    flag: "🇿🇦",
    name: "South Africa",
    pattern: /^[6|7|8]\d{8}$/,
  },
  {
    code: "+82",
    country: "KR",
    flag: "🇰🇷",
    name: "South Korea",
    pattern: /^1[0-9]\d{7,8}$/,
  },
  {
    code: "+211",
    country: "SS",
    flag: "🇸🇸",
    name: "South Sudan",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+34",
    country: "ES",
    flag: "🇪🇸",
    name: "Spain",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+94",
    country: "LK",
    flag: "🇱🇰",
    name: "Sri Lanka",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+249",
    country: "SD",
    flag: "🇸🇩",
    name: "Sudan",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+597",
    country: "SR",
    flag: "🇸🇷",
    name: "Suriname",
    pattern: /^[6|7|8]\d{6}$/,
  },
  {
    code: "+47",
    country: "SJ",
    flag: "🇸🇯",
    name: "Svalbard and Jan Mayen",
    pattern: /^[4|9]\d{7}$/,
  },
  {
    code: "+268",
    country: "SZ",
    flag: "🇸🇿",
    name: "Eswatini",
    pattern: /^[7|8]\d{7}$/,
  },
  {
    code: "+46",
    country: "SE",
    flag: "🇸🇪",
    name: "Sweden",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+41",
    country: "CH",
    flag: "🇨🇭",
    name: "Switzerland",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+963",
    country: "SY",
    flag: "🇸🇾",
    name: "Syria",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+886",
    country: "TW",
    flag: "🇹🇼",
    name: "Taiwan",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+992",
    country: "TJ",
    flag: "🇹🇯",
    name: "Tajikistan",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+255",
    country: "TZ",
    flag: "🇹🇿",
    name: "Tanzania",
    pattern: /^[6|7]\d{8}$/,
  },
  {
    code: "+66",
    country: "TH",
    flag: "🇹🇭",
    name: "Thailand",
    pattern: /^[6|8|9]\d{8}$/,
  },
  {
    code: "+228",
    country: "TG",
    flag: "🇹🇬",
    name: "Togo",
    pattern: /^[9]\d{7}$/,
  },
  {
    code: "+690",
    country: "TK",
    flag: "🇹🇰",
    name: "Tokelau",
    pattern: /^[7]\d{3}$/,
  },
  {
    code: "+676",
    country: "TO",
    flag: "🇹🇴",
    name: "Tonga",
    pattern: /^[7]\d{6}$/,
  },
  {
    code: "+1-868",
    country: "TT",
    flag: "🇹🇹",
    name: "Trinidad and Tobago",
    pattern: /^[6|7|8]\d{6}$/,
  },
  {
    code: "+216",
    country: "TN",
    flag: "🇹🇳",
    name: "Tunisia",
    pattern: /^[2|5|9]\d{7}$/,
  },
  {
    code: "+90",
    country: "TR",
    flag: "🇹🇷",
    name: "Turkey",
    pattern: /^[5]\d{9}$/,
  },
  {
    code: "+993",
    country: "TM",
    flag: "🇹🇲",
    name: "Turkmenistan",
    pattern: /^[6]\d{7}$/,
  },
  {
    code: "+1-649",
    country: "TC",
    flag: "🇹🇨",
    name: "Turks and Caicos Islands",
    pattern: /^[2|3|4]\d{6}$/,
  },
  {
    code: "+688",
    country: "TV",
    flag: "🇹🇻",
    name: "Tuvalu",
    pattern: /^[7]\d{5}$/,
  },
  {
    code: "+1-340",
    country: "VI",
    flag: "🇻🇮",
    name: "U.S. Virgin Islands",
    pattern: /^[3]\d{6}$/,
  },
  {
    code: "+256",
    country: "UG",
    flag: "🇺🇬",
    name: "Uganda",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+380",
    country: "UA",
    flag: "🇺🇦",
    name: "Ukraine",
    pattern: /^[3|6|7|9]\d{8}$/,
  },
  {
    code: "+971",
    country: "AE",
    flag: "🇦🇪",
    name: "United Arab Emirates",
    pattern: /^[5]\d{8}$/,
  },
  {
    code: "+44",
    country: "GB",
    flag: "🇬🇧",
    name: "United Kingdom",
    pattern: /^7\d{9}$/,
  },
  {
    code: "+1",
    country: "US",
    flag: "🇺🇸",
    name: "United States",
    pattern: /^[2-9]\d{9}$/,
  },
  {
    code: "+598",
    country: "UY",
    flag: "🇺🇾",
    name: "Uruguay",
    pattern: /^[9]\d{7}$/,
  },
  {
    code: "+998",
    country: "UZ",
    flag: "🇺🇿",
    name: "Uzbekistan",
    pattern: /^[9]\d{8}$/,
  },
  {
    code: "+678",
    country: "VU",
    flag: "🇻🇺",
    name: "Vanuatu",
    pattern: /^[5|7]\d{6}$/,
  },
  {
    code: "+379",
    country: "VA",
    flag: "🇻🇦",
    name: "Vatican",
    pattern: /^[3]\d{9}$/,
  },
  {
    code: "+58",
    country: "VE",
    flag: "🇻🇪",
    name: "Venezuela",
    pattern: /^[4]\d{9}$/,
  },
  {
    code: "+84",
    country: "VN",
    flag: "🇻🇳",
    name: "Vietnam",
    pattern: /^[3|5|7|8|9]\d{8}$/,
  },
  {
    code: "+681",
    country: "WF",
    flag: "🇼🇫",
    name: "Wallis and Futuna",
    pattern: /^[5|8]\d{5}$/,
  },
  {
    code: "+212",
    country: "EH",
    flag: "🇪🇭",
    name: "Western Sahara",
    pattern: /^[5|6]\d{8}$/,
  },
  {
    code: "+967",
    country: "YE",
    flag: "🇾🇪",
    name: "Yemen",
    pattern: /^[7]\d{8}$/,
  },
  {
    code: "+260",
    country: "ZM",
    flag: "🇿🇲",
    name: "Zambia",
    pattern: /^[7|9]\d{8}$/,
  },
  {
    code: "+263",
    country: "ZW",
    flag: "🇿🇼",
    name: "Zimbabwe",
    pattern: /^[7]\d{8}$/,
  },
].sort((a, b) => a.name.localeCompare(b.name));

export default countryCodes;
